import '../models/models.dart';

/// Offline / demo fallback data.
///
/// Every service falls back to this catalogue when the FastAPI backend is
/// unreachable (see the `!ApiClient.isBackendOnline` branches). The data is
/// intentionally rich and internally consistent (employees, contracts,
/// attendance, leave and payroll all reference the same people) so the UI
/// looks fully populated during a demo even with no backend running.
class MockDataService {
  static EmployeeModel currentEmployee = EmployeeModel(
    id: 'emp-001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@peoplepay360.io',
    jobTitle: 'Senior Software Architect',
    department: 'Finance & Tech Ops',
    workPhone: '+91 98765 43210',
    managerName: 'Sara Khan (HR Director)',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    timeOffBalance: 14,
    activeContractsCount: 1,
    attendancesCount: 22,
    payslipsCount: 12,
    badgeId: 'EMP-001',
    employeeType: 'Full-time',
    status: 'ACTIVE',
    dateOfJoining: '2024-04-01',
    bankName: 'HDFC Bank',
    bankAccountNumber: '5010-2288-4471',
  );

  static List<EmployeeModel> allEmployees = [
    EmployeeModel(
      id: 'emp-001',
      name: 'Aarav Sharma',
      email: 'aarav.sharma@peoplepay360.io',
      jobTitle: 'Senior Software Architect',
      department: 'Finance & Tech Ops',
      workPhone: '+91 98765 43210',
      managerName: 'Sara Khan',
      avatarUrl: '',
      timeOffBalance: 14,
      activeContractsCount: 1,
      attendancesCount: 22,
      payslipsCount: 12,
      badgeId: 'EMP-001',
      employeeType: 'Full-time',
      status: 'ACTIVE',
      dateOfJoining: '2024-04-01',
      bankName: 'HDFC Bank',
      bankAccountNumber: '5010-2288-4471',
    ),
    EmployeeModel(
      id: 'emp-002',
      name: 'Priya Patel',
      email: 'priya.patel@peoplepay360.io',
      jobTitle: 'Lead Payroll Analyst',
      department: 'Finance & Tech Ops',
      workPhone: '+91 98765 12345',
      managerName: 'Sara Khan',
      avatarUrl: '',
      timeOffBalance: 18,
      activeContractsCount: 1,
      attendancesCount: 20,
      payslipsCount: 12,
      badgeId: 'EMP-002',
      employeeType: 'Full-time',
      status: 'ACTIVE',
      dateOfJoining: '2023-06-12',
      bankName: 'ICICI Bank',
      bankAccountNumber: '6644-7781-2230',
    ),
    EmployeeModel(
      id: 'emp-003',
      name: 'Rajesh Kumar',
      email: 'rajesh.kumar@peoplepay360.io',
      jobTitle: 'Senior HR Operations Manager',
      department: 'Human Resources',
      workPhone: '+91 98765 67890',
      managerName: 'Sara Khan',
      avatarUrl: '',
      timeOffBalance: 10,
      activeContractsCount: 1,
      attendancesCount: 21,
      payslipsCount: 12,
      badgeId: 'EMP-003',
      employeeType: 'Full-time',
      status: 'ACTIVE',
      dateOfJoining: '2022-02-01',
      bankName: 'SBI',
      bankAccountNumber: '3391-0087-5512',
    ),
    EmployeeModel(
      id: 'emp-004',
      name: 'Sara Khan',
      email: 'sara.khan@peoplepay360.io',
      jobTitle: 'HR Director',
      department: 'Human Resources',
      workPhone: '+91 90210 33445',
      managerName: 'Board of Directors',
      avatarUrl: '',
      timeOffBalance: 22,
      activeContractsCount: 1,
      attendancesCount: 23,
      payslipsCount: 12,
      badgeId: 'EMP-004',
      employeeType: 'Full-time',
      status: 'ACTIVE',
      dateOfJoining: '2021-01-04',
      bankName: 'Axis Bank',
      bankAccountNumber: '7720-5541-0098',
    ),
    EmployeeModel(
      id: 'emp-005',
      name: 'Vikram Singh',
      email: 'vikram.singh@peoplepay360.io',
      jobTitle: 'Backend Engineer',
      department: 'Engineering',
      workPhone: '+91 99887 66554',
      managerName: 'Aarav Sharma',
      avatarUrl: '',
      timeOffBalance: 12,
      activeContractsCount: 1,
      attendancesCount: 19,
      payslipsCount: 8,
      badgeId: 'EMP-005',
      employeeType: 'Full-time',
      status: 'ACTIVE',
      dateOfJoining: '2024-09-16',
      bankName: 'Kotak Mahindra',
      bankAccountNumber: '4412-6690-3388',
    ),
    EmployeeModel(
      id: 'emp-006',
      name: 'Neha Verma',
      email: 'neha.verma@peoplepay360.io',
      jobTitle: 'UX Designer',
      department: 'Design',
      workPhone: '+91 97654 32109',
      managerName: 'Aarav Sharma',
      avatarUrl: '',
      timeOffBalance: 16,
      activeContractsCount: 1,
      attendancesCount: 20,
      payslipsCount: 10,
      badgeId: 'EMP-006',
      employeeType: 'Full-time',
      status: 'ACTIVE',
      dateOfJoining: '2024-01-22',
      bankName: 'HDFC Bank',
      bankAccountNumber: '5010-9987-1123',
    ),
    EmployeeModel(
      id: 'emp-007',
      name: 'Mohammed Ali',
      email: 'mohammed.ali@peoplepay360.io',
      jobTitle: 'Sales Executive',
      department: 'Sales',
      workPhone: '+91 96543 21087',
      managerName: 'Rajesh Kumar',
      avatarUrl: '',
      timeOffBalance: 9,
      activeContractsCount: 1,
      attendancesCount: 18,
      payslipsCount: 6,
      badgeId: 'EMP-007',
      employeeType: 'Contract',
      status: 'ACTIVE',
      dateOfJoining: '2025-03-03',
      bankName: 'Yes Bank',
      bankAccountNumber: '8890-2214-6675',
    ),
    EmployeeModel(
      id: 'emp-008',
      name: 'Ananya Reddy',
      email: 'ananya.reddy@peoplepay360.io',
      jobTitle: 'QA Engineer',
      department: 'Engineering',
      workPhone: '+91 95432 10876',
      managerName: 'Aarav Sharma',
      avatarUrl: '',
      timeOffBalance: 15,
      activeContractsCount: 1,
      attendancesCount: 21,
      payslipsCount: 9,
      badgeId: 'EMP-008',
      employeeType: 'Full-time',
      status: 'ACTIVE',
      dateOfJoining: '2024-07-08',
      bankName: 'IDFC First',
      bankAccountNumber: '2231-7788-4409',
    ),
    EmployeeModel(
      id: 'emp-009',
      name: 'Karan Mehta',
      email: 'karan.mehta@peoplepay360.io',
      jobTitle: 'Support Specialist',
      department: 'Customer Support',
      workPhone: '+91 94321 09875',
      managerName: 'Rajesh Kumar',
      avatarUrl: '',
      timeOffBalance: 7,
      activeContractsCount: 1,
      attendancesCount: 17,
      payslipsCount: 5,
      badgeId: 'EMP-009',
      employeeType: 'Full-time',
      status: 'ON_LEAVE',
      dateOfJoining: '2025-05-19',
      bankName: 'SBI',
      bankAccountNumber: '3391-6654-8890',
    ),
  ];

  static List<AttendanceModel> attendances = [
    AttendanceModel(id: 'att-01', dateStr: '2026-09-05', checkInTime: '09:02 AM', checkOutTime: null, status: 'PRESENT', workedHours: 5.5, employeeName: 'Aarav Sharma', employeeId: 'emp-001'),
    AttendanceModel(id: 'att-02', dateStr: '2026-09-04', checkInTime: '09:15 AM', checkOutTime: '06:10 PM', status: 'LATE', workedHours: 8.5, employeeName: 'Aarav Sharma', employeeId: 'emp-001'),
    AttendanceModel(id: 'att-03', dateStr: '2026-09-03', checkInTime: '08:58 AM', checkOutTime: '06:00 PM', status: 'PRESENT', workedHours: 9.0, employeeName: 'Aarav Sharma', employeeId: 'emp-001'),
    AttendanceModel(id: 'att-04', dateStr: '2026-09-02', checkInTime: '09:00 AM', checkOutTime: '05:55 PM', status: 'PRESENT', workedHours: 8.9, employeeName: 'Aarav Sharma', employeeId: 'emp-001'),
    AttendanceModel(id: 'att-05', dateStr: '2026-09-01', checkInTime: '09:05 AM', checkOutTime: '06:15 PM', status: 'PRESENT', workedHours: 9.1, employeeName: 'Aarav Sharma', employeeId: 'emp-001'),
    AttendanceModel(id: 'att-06', dateStr: '2026-08-31', checkInTime: '08:55 AM', checkOutTime: '06:02 PM', status: 'PRESENT', workedHours: 9.0, employeeName: 'Aarav Sharma', employeeId: 'emp-001'),
    AttendanceModel(id: 'att-07', dateStr: '2026-09-05', checkInTime: '09:20 AM', checkOutTime: null, status: 'LATE', workedHours: 5.2, employeeName: 'Priya Patel', employeeId: 'emp-002'),
    AttendanceModel(id: 'att-08', dateStr: '2026-09-05', checkInTime: '08:45 AM', checkOutTime: null, status: 'PRESENT', workedHours: 5.8, employeeName: 'Vikram Singh', employeeId: 'emp-005'),
    AttendanceModel(id: 'att-09', dateStr: '2026-09-05', checkInTime: '--', checkOutTime: null, status: 'ON_LEAVE', workedHours: 0.0, employeeName: 'Karan Mehta', employeeId: 'emp-009'),
    AttendanceModel(id: 'att-10', dateStr: '2026-09-05', checkInTime: '--', checkOutTime: null, status: 'ABSENT', workedHours: 0.0, employeeName: 'Mohammed Ali', employeeId: 'emp-007'),
    AttendanceModel(id: 'att-11', dateStr: '2026-09-04', checkInTime: '09:01 AM', checkOutTime: '06:05 PM', status: 'PRESENT', workedHours: 9.0, employeeName: 'Neha Verma', employeeId: 'emp-006'),
    AttendanceModel(id: 'att-12', dateStr: '2026-09-04', checkInTime: '08:50 AM', checkOutTime: '05:45 PM', status: 'PRESENT', workedHours: 8.9, employeeName: 'Ananya Reddy', employeeId: 'emp-008'),
    AttendanceModel(id: 'att-13', dateStr: '2026-09-04', checkInTime: '09:32 AM', checkOutTime: '06:40 PM', status: 'LATE', workedHours: 9.1, employeeName: 'Rajesh Kumar', employeeId: 'emp-003'),
    AttendanceModel(id: 'att-14', dateStr: '2026-09-03', checkInTime: '08:40 AM', checkOutTime: '05:50 PM', status: 'PRESENT', workedHours: 9.2, employeeName: 'Sara Khan', employeeId: 'emp-004'),
  ];

  static List<TimeOffRequestModel> timeOffRequests = [
    TimeOffRequestModel(id: 'req-01', typeName: 'Paid Time Off (PTO)', startDate: '2026-09-15', endDate: '2026-09-18', daysCount: 4.0, status: 'PENDING', reason: 'Family Annual Event', employeeName: 'Aarav Sharma'),
    TimeOffRequestModel(id: 'req-02', typeName: 'Sick Leave', startDate: '2026-08-10', endDate: '2026-08-10', daysCount: 1.0, status: 'APPROVED', reason: 'Fever & Doctor Visit', employeeName: 'Aarav Sharma'),
    TimeOffRequestModel(id: 'req-03', typeName: 'Casual Leave', startDate: '2026-07-01', endDate: '2026-07-02', daysCount: 2.0, status: 'APPROVED', reason: 'Personal errands', employeeName: 'Aarav Sharma'),
    TimeOffRequestModel(id: 'req-04', typeName: 'Paid Time Off (PTO)', startDate: '2026-09-22', endDate: '2026-09-26', daysCount: 5.0, status: 'PENDING', reason: 'Diwali travel to hometown', employeeName: 'Priya Patel'),
    TimeOffRequestModel(id: 'req-05', typeName: 'Sick Leave', startDate: '2026-09-02', endDate: '2026-09-03', daysCount: 2.0, status: 'APPROVED', reason: 'Viral flu, doctor advised rest', employeeName: 'Vikram Singh'),
    TimeOffRequestModel(id: 'req-06', typeName: 'Comp Off', startDate: '2026-09-12', endDate: '2026-09-12', daysCount: 1.0, status: 'PENDING', reason: 'Weekend payroll deployment (Aug 30)', employeeName: 'Neha Verma'),
    TimeOffRequestModel(id: 'req-07', typeName: 'Maternity Leave', startDate: '2026-10-01', endDate: '2026-12-30', daysCount: 90.0, status: 'APPROVED', reason: 'Maternity leave as per policy', employeeName: 'Ananya Reddy'),
    TimeOffRequestModel(id: 'req-08', typeName: 'Unpaid Leave', startDate: '2026-08-25', endDate: '2026-08-27', daysCount: 3.0, status: 'REFUSED', reason: 'Insufficient balance, LOP requested', employeeName: 'Mohammed Ali'),
  ];

  /// Leave balances / allocations per employee per leave type.
  /// Kept as maps so screens that render an allocation matrix have data even
  /// without a dedicated model class.
  static List<Map<String, dynamic>> leaveAllocations = [
    {'employeeName': 'Aarav Sharma', 'type': 'Paid Time Off (PTO)', 'allocated': 24.0, 'taken': 10.0, 'remaining': 14.0, 'status': 'APPROVED', 'validity': '2026'},
    {'employeeName': 'Aarav Sharma', 'type': 'Sick Leave', 'allocated': 12.0, 'taken': 4.0, 'remaining': 8.0, 'status': 'APPROVED', 'validity': '2026'},
    {'employeeName': 'Aarav Sharma', 'type': 'Comp Off', 'allocated': 2.0, 'taken': 0.0, 'remaining': 2.0, 'status': 'APPROVED', 'validity': '2026'},
    {'employeeName': 'Priya Patel', 'type': 'Paid Time Off (PTO)', 'allocated': 24.0, 'taken': 6.0, 'remaining': 18.0, 'status': 'APPROVED', 'validity': '2026'},
    {'employeeName': 'Priya Patel', 'type': 'Sick Leave', 'allocated': 12.0, 'taken': 2.0, 'remaining': 10.0, 'status': 'APPROVED', 'validity': '2026'},
    {'employeeName': 'Vikram Singh', 'type': 'Paid Time Off (PTO)', 'allocated': 24.0, 'taken': 12.0, 'remaining': 12.0, 'status': 'APPROVED', 'validity': '2026'},
    {'employeeName': 'Neha Verma', 'type': 'Comp Off', 'allocated': 3.0, 'taken': 1.0, 'remaining': 2.0, 'status': 'PENDING', 'validity': '2026'},
    {'employeeName': 'Ananya Reddy', 'type': 'Maternity Leave', 'allocated': 90.0, 'taken': 0.0, 'remaining': 90.0, 'status': 'APPROVED', 'validity': '2026'},
  ];

  static List<ContractModel> contracts = [
    ContractModel(id: 'con-01', refCode: 'CON/2026/0042', employeeName: 'Aarav Sharma', department: 'Finance & Tech Ops', startDate: '2026-01-01', wageMonthly: 100000.0, status: 'RUNNING', structureName: 'Regular Employee Base'),
    ContractModel(id: 'con-02', refCode: 'CON/2025/0011', employeeName: 'Aarav Sharma', department: 'Software Dev', startDate: '2025-01-01', endDate: '2025-12-31', wageMonthly: 85000.0, status: 'EXPIRED', structureName: 'Regular Employee Base'),
    ContractModel(id: 'con-03', refCode: 'CON/2026/0043', employeeName: 'Priya Patel', department: 'Finance & Tech Ops', startDate: '2026-01-01', wageMonthly: 92000.0, status: 'RUNNING', structureName: 'Regular Employee Base'),
    ContractModel(id: 'con-04', refCode: 'CON/2026/0044', employeeName: 'Vikram Singh', department: 'Engineering', startDate: '2026-02-01', wageMonthly: 78000.0, status: 'RUNNING', structureName: 'Regular Employee Base'),
    ContractModel(id: 'con-05', refCode: 'CON/2026/0045', employeeName: 'Mohammed Ali', department: 'Sales', startDate: '2026-03-01', endDate: '2026-08-31', wageMonthly: 55000.0, status: 'EXPIRED', structureName: 'Contractor Base'),
    ContractModel(id: 'con-06', refCode: 'CON/2026/0051', employeeName: 'Neha Verma', department: 'Design', startDate: '2026-01-15', wageMonthly: 70000.0, status: 'RUNNING', structureName: 'Regular Employee Base'),
    ContractModel(id: 'con-07', refCode: 'CON/2026/0052', employeeName: 'Karan Mehta', department: 'Customer Support', startDate: '2026-06-01', wageMonthly: 48000.0, status: 'DRAFT', structureName: 'Regular Employee Base'),
  ];

  static List<SalaryRuleModel> salaryRules = [
    SalaryRuleModel(id: 'r-1', name: 'Basic Salary', code: 'BASIC', sequence: 1, category: 'BASIC', computationType: 'PERCENTAGE', percentageBase: 'WAGE', percentageRate: 50.0, pythonCode: "result = contract.wage * 0.50"),
    SalaryRuleModel(id: 'r-2', name: 'House Rent Allowance', code: 'HRA', sequence: 10, category: 'ALLOWANCE', computationType: 'PERCENTAGE', percentageBase: 'BASIC', percentageRate: 40.0, pythonCode: "result = categories['BASIC'] * 0.40"),
    SalaryRuleModel(id: 'r-3', name: 'Standard Allowance', code: 'STD', sequence: 20, category: 'ALLOWANCE', computationType: 'FIXED', fixedAmount: 10000.0, pythonCode: "result = 10000.0"),
    SalaryRuleModel(id: 'r-4', name: 'Gross Salary', code: 'GROSS', sequence: 60, category: 'GROSS', computationType: 'PYTHON_CODE', pythonCode: "result = categories['BASIC'] + categories['ALLOWANCE']"),
    SalaryRuleModel(id: 'r-5', name: 'Provident Fund', code: 'PF', sequence: 80, category: 'DEDUCTION', computationType: 'PERCENTAGE', percentageBase: 'BASIC', percentageRate: 6.0, pythonCode: "result = categories['BASIC'] * 0.06"),
    SalaryRuleModel(id: 'r-6', name: 'Professional Tax', code: 'PT', sequence: 100, category: 'DEDUCTION', computationType: 'FIXED', fixedAmount: 2000.0, pythonCode: "result = 2000.0"),
    SalaryRuleModel(id: 'r-7', name: 'Net Salary', code: 'NET', sequence: 110, category: 'NET', computationType: 'PYTHON_CODE', pythonCode: "result = categories['GROSS'] - categories['DEDUCTION']"),
  ];

  static List<PayslipModel> payslips = [
    PayslipModel(
      id: 'pay-01',
      refCode: 'PAY/2026/08',
      employeeName: 'Aarav Sharma',
      periodStart: '2026-08-01',
      periodEnd: '2026-08-31',
      grossAmount: 80000.0,
      netAmount: 75000.0,
      status: 'DONE',
      lines: [
        PayslipLineModel(ruleName: 'Basic Salary', ruleCode: 'BASIC', category: 'BASIC', amount: 50000.0),
        PayslipLineModel(ruleName: 'House Rent Allowance', ruleCode: 'HRA', category: 'ALLOWANCE', amount: 20000.0),
        PayslipLineModel(ruleName: 'Standard Allowance', ruleCode: 'STD', category: 'ALLOWANCE', amount: 10000.0),
        PayslipLineModel(ruleName: 'Gross Salary', ruleCode: 'GROSS', category: 'GROSS', amount: 80000.0),
        PayslipLineModel(ruleName: 'Provident Fund', ruleCode: 'PF', category: 'DEDUCTION', amount: -3000.0),
        PayslipLineModel(ruleName: 'Professional Tax', ruleCode: 'PT', category: 'DEDUCTION', amount: -2000.0),
        PayslipLineModel(ruleName: 'Net Salary', ruleCode: 'NET', category: 'NET', amount: 75000.0),
      ],
    ),
    PayslipModel(
      id: 'pay-02',
      refCode: 'PAY/2026/07',
      employeeName: 'Aarav Sharma',
      periodStart: '2026-07-01',
      periodEnd: '2026-07-31',
      grossAmount: 80000.0,
      netAmount: 75000.0,
      status: 'DONE',
      lines: [
        PayslipLineModel(ruleName: 'Basic Salary', ruleCode: 'BASIC', category: 'BASIC', amount: 50000.0),
        PayslipLineModel(ruleName: 'House Rent Allowance', ruleCode: 'HRA', category: 'ALLOWANCE', amount: 20000.0),
        PayslipLineModel(ruleName: 'Standard Allowance', ruleCode: 'STD', category: 'ALLOWANCE', amount: 10000.0),
        PayslipLineModel(ruleName: 'Gross Salary', ruleCode: 'GROSS', category: 'GROSS', amount: 80000.0),
        PayslipLineModel(ruleName: 'Provident Fund', ruleCode: 'PF', category: 'DEDUCTION', amount: -3000.0),
        PayslipLineModel(ruleName: 'Professional Tax', ruleCode: 'PT', category: 'DEDUCTION', amount: -2000.0),
        PayslipLineModel(ruleName: 'Net Salary', ruleCode: 'NET', category: 'NET', amount: 75000.0),
      ],
    ),
    PayslipModel(
      id: 'pay-03',
      refCode: 'PAY/2026/08-PP',
      employeeName: 'Priya Patel',
      periodStart: '2026-08-01',
      periodEnd: '2026-08-31',
      grossAmount: 73600.0,
      netAmount: 68840.0,
      status: 'DONE',
      lines: [
        PayslipLineModel(ruleName: 'Basic Salary', ruleCode: 'BASIC', category: 'BASIC', amount: 46000.0),
        PayslipLineModel(ruleName: 'House Rent Allowance', ruleCode: 'HRA', category: 'ALLOWANCE', amount: 18400.0),
        PayslipLineModel(ruleName: 'Standard Allowance', ruleCode: 'STD', category: 'ALLOWANCE', amount: 10000.0),
        PayslipLineModel(ruleName: 'Gross Salary', ruleCode: 'GROSS', category: 'GROSS', amount: 73600.0),
        PayslipLineModel(ruleName: 'Provident Fund', ruleCode: 'PF', category: 'DEDUCTION', amount: -2760.0),
        PayslipLineModel(ruleName: 'Professional Tax', ruleCode: 'PT', category: 'DEDUCTION', amount: -2000.0),
        PayslipLineModel(ruleName: 'Net Salary', ruleCode: 'NET', category: 'NET', amount: 68840.0),
      ],
    ),
    PayslipModel(
      id: 'pay-04',
      refCode: 'PAY/2026/08-VS',
      employeeName: 'Vikram Singh',
      periodStart: '2026-08-01',
      periodEnd: '2026-08-31',
      grossAmount: 62400.0,
      netAmount: 58060.0,
      status: 'DRAFT',
      lines: [
        PayslipLineModel(ruleName: 'Basic Salary', ruleCode: 'BASIC', category: 'BASIC', amount: 39000.0),
        PayslipLineModel(ruleName: 'House Rent Allowance', ruleCode: 'HRA', category: 'ALLOWANCE', amount: 15600.0),
        PayslipLineModel(ruleName: 'Standard Allowance', ruleCode: 'STD', category: 'ALLOWANCE', amount: 10000.0),
        PayslipLineModel(ruleName: 'Gross Salary', ruleCode: 'GROSS', category: 'GROSS', amount: 62400.0),
        PayslipLineModel(ruleName: 'Provident Fund', ruleCode: 'PF', category: 'DEDUCTION', amount: -2340.0),
        PayslipLineModel(ruleName: 'Professional Tax', ruleCode: 'PT', category: 'DEDUCTION', amount: -2000.0),
        PayslipLineModel(ruleName: 'Net Salary', ruleCode: 'NET', category: 'NET', amount: 58060.0),
      ],
    ),
  ];

  static List<EscalationTicketModel> escalationTickets = [
    EscalationTicketModel(
      id: 'esc-01',
      ticketNo: 'ESC/2026/0042',
      questionText: 'Can I carry forward my unused 14 PTO days into Q1 next year?',
      category: 'LEAVE_POLICY',
      status: 'ASSIGNED',
      priority: 'HIGH',
      slaDueAt: '2026-09-06 18:00',
      answerText: null,
      answeredBy: 'Sara Khan (HR Director)',
      retrievalConfidence: 0.38,
    ),
    EscalationTicketModel(
      id: 'esc-02',
      ticketNo: 'ESC/2026/0038',
      questionText: 'Is Professional Tax (PT) calculated on gross or basic salary in Maharashtra?',
      category: 'TAX_STATUTORY',
      status: 'ANSWERED',
      priority: 'NORMAL',
      slaDueAt: '2026-09-04 12:00',
      answerText: 'Professional Tax in Maharashtra is a fixed statutory deduction of ₹2,000/year (₹200/month except February which is ₹300). It is independent of basic salary.',
      answeredBy: 'Priya Patel (Payroll Mgr)',
      retrievalConfidence: 0.41,
    ),
    EscalationTicketModel(
      id: 'esc-03',
      ticketNo: 'ESC/2026/0051',
      questionText: 'What is the notice period for a contract employee resigning mid-term?',
      category: 'CONTRACT',
      status: 'OPEN',
      priority: 'NORMAL',
      slaDueAt: '2026-09-07 10:00',
      answerText: null,
      answeredBy: null,
      retrievalConfidence: 0.29,
    ),
    EscalationTicketModel(
      id: 'esc-04',
      ticketNo: 'ESC/2026/0055',
      questionText: 'My September attendance shows a missed check-out on Sep 5. Will it affect payroll?',
      category: 'ATTENDANCE',
      status: 'OPEN',
      priority: 'HIGH',
      slaDueAt: '2026-09-06 16:00',
      answerText: null,
      answeredBy: null,
      retrievalConfidence: 0.44,
    ),
  ];

  static List<WorkingScheduleModel> workingSchedules = [
    WorkingScheduleModel(
      id: 'ws-01',
      name: 'Standard 40 Hours / Week',
      averageHoursPerWeek: 40,
      daysPerWeek: 5,
      timezone: 'Asia/Kolkata',
    ),
    WorkingScheduleModel(
      id: 'ws-02',
      name: 'Night Shift 45 Hours / Week',
      averageHoursPerWeek: 45,
      daysPerWeek: 5,
      timezone: 'Asia/Kolkata',
    ),
    WorkingScheduleModel(
      id: 'ws-03',
      name: 'Part-Time 24 Hours / Week',
      averageHoursPerWeek: 24,
      daysPerWeek: 4,
      timezone: 'Asia/Kolkata',
    ),
    WorkingScheduleModel(
      id: 'ws-04',
      name: 'Hybrid 36 Hours / Week',
      averageHoursPerWeek: 36,
      daysPerWeek: 5,
      timezone: 'Asia/Kolkata',
    ),
  ];

  static List<TimeOffTypeModel> timeOffTypes = [
    TimeOffTypeModel(
      id: 'tot-01',
      name: 'Paid Time Off',
      code: 'PTO',
      requiresApproval: true,
      color: '#0d9488', // odooTeal
    ),
    TimeOffTypeModel(
      id: 'tot-02',
      name: 'Sick Leave',
      code: 'SL',
      requiresApproval: false,
      color: '#e11d48', // odooRed
    ),
    TimeOffTypeModel(
      id: 'tot-03',
      name: 'Maternity Leave',
      code: 'ML',
      requiresApproval: true,
      color: '#57344f', // odooAubergine
    ),
    TimeOffTypeModel(
      id: 'tot-04',
      name: 'Compensatory Off',
      code: 'COMP',
      requiresApproval: true,
      color: '#2563eb', // blue
    ),
    TimeOffTypeModel(
      id: 'tot-05',
      name: 'Unpaid Leave',
      code: 'LOP',
      requiresApproval: true,
      color: '#64748b', // slate
    ),
  ];

  static List<SalaryStructureModel> salaryStructures = [
    SalaryStructureModel(
      id: 'struct-01',
      name: 'Regular Employee Base',
      reference: 'BASE-IN',
      country: 'India',
      ruleIds: ['BASIC', 'HRA', 'STD', 'GROSS', 'PF', 'PT', 'NET'],
    ),
    SalaryStructureModel(
      id: 'struct-02',
      name: 'Contractor Base',
      reference: 'CONT-IN',
      country: 'India',
      ruleIds: ['BASIC', 'TDS', 'NET'],
    ),
    SalaryStructureModel(
      id: 'struct-03',
      name: 'Intern Stipend',
      reference: 'INTERN-IN',
      country: 'India',
      ruleIds: ['BASIC', 'NET'],
    ),
  ];
}
